version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - echo In buildspec-setup.yml Build started on `date`
      - >-
        aws s3api list-buckets --query 'Buckets[?starts_with(Name,
        `deoa-wkshop-abcd`) == `true`].[Name]' --output text | xargs -I {} aws s3 rb s3://{} --force
      - 'sleep 10'
      - 'aws s3 mb s3://deoa-wkshop-abcd'
      - 'aws s3 sync . s3://deoa-wkshop-abcd'
      - cd samples/ec2
      - zip deoa-ec2-examples.zip *.*
      - 'aws s3 sync . s3://deoa-wkshop-abcd'
      - cd ../beanstalk
      - zip deoa-beanstalk-examples.zip *.*
      - 'aws s3 sync . s3://deoa-wkshop-abcd'
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'
